// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum MAMapRectCorner {
  MAMapRectCornerTopLeft /* 1<<0 */,
  MAMapRectCornerTopRight /* 1<<1 */,
  MAMapRectCornerBottomLeft /* 1<<2 */,
  MAMapRectCornerBottomRight /* 1<<3 */,
  MAMapRectCornerAllCorners /* ~0 */
}

extension MAMapRectCornerToX on MAMapRectCorner {
  int toValue() {
    switch (this) {
      case MAMapRectCorner.MAMapRectCornerTopLeft: return 1<<0;
      case MAMapRectCorner.MAMapRectCornerTopRight: return 1<<1;
      case MAMapRectCorner.MAMapRectCornerBottomLeft: return 1<<2;
      case MAMapRectCorner.MAMapRectCornerBottomRight: return 1<<3;
      case MAMapRectCorner.MAMapRectCornerAllCorners: return ~0;
      default: return 0;
    }
  }
}

extension MAMapRectCornerFromX on int {
  MAMapRectCorner toMAMapRectCorner() {
    switch (this) {
      case const(1<<0): return MAMapRectCorner.MAMapRectCornerTopLeft;
      case const(1<<1): return MAMapRectCorner.MAMapRectCornerTopRight;
      case const(1<<2): return MAMapRectCorner.MAMapRectCornerBottomLeft;
      case const(1<<3): return MAMapRectCorner.MAMapRectCornerBottomRight;
      case const(~0): return MAMapRectCorner.MAMapRectCornerAllCorners;
      default: return MAMapRectCorner.values[this + 1<<0];
    }
  }
}